// <auto-generated />
using System;
using Infra.Database.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Infra.Migrations
{
    [DbContext(typeof(MsgContext))]
    [Migration("20210907214238_CreateMessagesAndGroupsTable")]
    partial class CreateMessagesAndGroupsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mensageiro")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Domain.BlockInfo", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.HasKey("Guid")
                        .HasName("pk_blocks");

                    b.ToTable("blocks");
                });

            modelBuilder.Entity("Domain.ChatGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_chatgroups");

                    b.ToTable("chatgroups");
                });

            modelBuilder.Entity("Domain.Contact", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<Guid?>("BlockGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("blockguid");

                    b.Property<Guid>("ContactUserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("contactuserguid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("userguid");

                    b.HasKey("Guid")
                        .HasName("pk_contacts");

                    b.HasIndex("BlockGuid")
                        .IsUnique()
                        .HasDatabaseName("ix_contacts_blockguid");

                    b.HasIndex("ContactUserGuid")
                        .HasDatabaseName("ix_contacts_contactuserguid");

                    b.HasIndex("UserGuid")
                        .HasDatabaseName("ix_contacts_userguid");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("Domain.ContactInvitation", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<Guid>("InvitedUserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("inviteduserguid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("userguid");

                    b.HasKey("Guid")
                        .HasName("pk_contactinvitation");

                    b.HasIndex("InvitedUserGuid")
                        .HasDatabaseName("ix_contactinvitation_inviteduserguid");

                    b.HasIndex("UserGuid")
                        .HasDatabaseName("ix_contactinvitation_userguid");

                    b.ToTable("contactinvitation");
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("groupid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sentat");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_messages_groupid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_messages_userid");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.HasKey("Guid")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Domain.UserAccount", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("userguid");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashedpassword");

                    b.HasKey("UserGuid")
                        .HasName("pk_useraccounts");

                    b.ToTable("useraccounts");
                });

            modelBuilder.Entity("Domain.UserGroupRelationship", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("groupid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("GroupId", "UserId")
                        .HasName("pk_usergrouprelationships");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_usergrouprelationships_groupid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usergrouprelationships_userid");

                    b.ToTable("usergrouprelationships");
                });

            modelBuilder.Entity("Domain.Contact", b =>
                {
                    b.HasOne("Domain.BlockInfo", "Block")
                        .WithOne()
                        .HasForeignKey("Domain.Contact", "BlockGuid")
                        .HasConstraintName("blockguid");

                    b.HasOne("Domain.User", "ContactUser")
                        .WithMany()
                        .HasForeignKey("ContactUserGuid")
                        .HasConstraintName("contactuserguid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .HasConstraintName("userguid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("ContactUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.ContactInvitation", b =>
                {
                    b.HasOne("Domain.User", "InvitedUser")
                        .WithMany()
                        .HasForeignKey("InvitedUserGuid")
                        .HasConstraintName("inviteduserguid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .HasConstraintName("userguid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.HasOne("Domain.ChatGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .HasConstraintName("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.UserAccount", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("Domain.UserAccount", "UserGuid")
                        .HasConstraintName("fk_useraccounts_users_userguid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.UserGroupRelationship", b =>
                {
                    b.HasOne("Domain.ChatGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .HasConstraintName("fk_usergrouprelationships_chatgroups_groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_usergrouprelationships_users_userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
