// <auto-generated />
using System;
using Infra.Database.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Infra.Migrations
{
    [DbContext(typeof(MsgContext))]
    partial class MsgContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mensageiro")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Domain.BlockInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.HasKey("Id")
                        .HasName("pk_blocks");

                    b.ToTable("blocks");
                });

            modelBuilder.Entity("Domain.ChatGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_chatgroups");

                    b.ToTable("chatgroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b903f40-1f53-4c5b-beb3-b3cf5ac21ff3")
                        },
                        new
                        {
                            Id = new Guid("998f3c13-78f1-42cb-977d-dfa121ae3609")
                        },
                        new
                        {
                            Id = new Guid("04b8a481-221f-4bef-a5af-306204ced472")
                        },
                        new
                        {
                            Id = new Guid("649a3553-5da3-4ce8-ad49-c51714bef758")
                        },
                        new
                        {
                            Id = new Guid("ffb2fe92-612f-41c2-b77c-b9027e430be1")
                        },
                        new
                        {
                            Id = new Guid("0d9bcff0-57ea-45ed-a566-3c829942e34b")
                        },
                        new
                        {
                            Id = new Guid("167096b8-e066-46f0-a90e-446b540d331d")
                        },
                        new
                        {
                            Id = new Guid("169e4880-3d26-4e5b-a14c-c1e214d17370")
                        },
                        new
                        {
                            Id = new Guid("a125b75d-abce-42f6-b876-f18978312f4d")
                        },
                        new
                        {
                            Id = new Guid("a498dcb0-3f6d-4f39-a354-9af1e18f3d9e")
                        },
                        new
                        {
                            Id = new Guid("95bba9f6-c661-425f-9902-dcb08e00d949")
                        },
                        new
                        {
                            Id = new Guid("9ed9e0da-4c7e-4071-82ea-7f3617abde35")
                        },
                        new
                        {
                            Id = new Guid("7dc46b57-9f16-4857-9951-60b65e8d68ab")
                        },
                        new
                        {
                            Id = new Guid("a5836c08-6aa5-4d85-8c18-af8019cdec9f")
                        },
                        new
                        {
                            Id = new Guid("8f525afe-0b26-4e29-8edb-ebaa62721a4e")
                        });
                });

            modelBuilder.Entity("Domain.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("blockid");

                    b.Property<Guid>("ContactUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("contactuserid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("groupid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("BlockId")
                        .IsUnique()
                        .HasDatabaseName("ix_contacts_blockid");

                    b.HasIndex("ContactUserId")
                        .HasDatabaseName("ix_contacts_contactuserid");

                    b.HasIndex("GroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_contacts_groupid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_contacts_userid");

                    b.ToTable("contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b17a4dd-1979-4d0c-97fe-23ab21427c5e"),
                            ContactUserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d"),
                            GroupId = new Guid("2b903f40-1f53-4c5b-beb3-b3cf5ac21ff3"),
                            UserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2")
                        },
                        new
                        {
                            Id = new Guid("e2751d60-5186-4d62-9031-66db81bdc1a7"),
                            ContactUserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596"),
                            GroupId = new Guid("998f3c13-78f1-42cb-977d-dfa121ae3609"),
                            UserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2")
                        },
                        new
                        {
                            Id = new Guid("3947be5d-b018-45fa-9850-957e2ec079fa"),
                            ContactUserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5"),
                            GroupId = new Guid("04b8a481-221f-4bef-a5af-306204ced472"),
                            UserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2")
                        },
                        new
                        {
                            Id = new Guid("6705141b-072b-44b0-9712-fb1fde986346"),
                            ContactUserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162"),
                            GroupId = new Guid("649a3553-5da3-4ce8-ad49-c51714bef758"),
                            UserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2")
                        },
                        new
                        {
                            Id = new Guid("b313be69-5e66-4f93-bc56-b0661bc7dd15"),
                            ContactUserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51"),
                            GroupId = new Guid("ffb2fe92-612f-41c2-b77c-b9027e430be1"),
                            UserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2")
                        },
                        new
                        {
                            Id = new Guid("3a7eadd1-c00c-470b-a18d-dfce31c28b01"),
                            ContactUserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2"),
                            GroupId = new Guid("2b903f40-1f53-4c5b-beb3-b3cf5ac21ff3"),
                            UserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d")
                        },
                        new
                        {
                            Id = new Guid("c9966289-f5a5-4caa-80cc-0be3b812094a"),
                            ContactUserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596"),
                            GroupId = new Guid("0d9bcff0-57ea-45ed-a566-3c829942e34b"),
                            UserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d")
                        },
                        new
                        {
                            Id = new Guid("44b88124-4da1-4bf7-91f5-f04346b452ab"),
                            ContactUserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5"),
                            GroupId = new Guid("167096b8-e066-46f0-a90e-446b540d331d"),
                            UserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d")
                        },
                        new
                        {
                            Id = new Guid("2bf78af2-7e55-44fb-9017-ecb77de24cb1"),
                            ContactUserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162"),
                            GroupId = new Guid("169e4880-3d26-4e5b-a14c-c1e214d17370"),
                            UserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d")
                        },
                        new
                        {
                            Id = new Guid("6fd926de-c320-4834-b321-8ffef4807650"),
                            ContactUserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51"),
                            GroupId = new Guid("a125b75d-abce-42f6-b876-f18978312f4d"),
                            UserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d")
                        },
                        new
                        {
                            Id = new Guid("e1f830b8-8974-44d4-b54b-8aa49ee03c5d"),
                            ContactUserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2"),
                            GroupId = new Guid("998f3c13-78f1-42cb-977d-dfa121ae3609"),
                            UserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596")
                        },
                        new
                        {
                            Id = new Guid("71253f3e-484b-42ac-99f1-8348299b55ad"),
                            ContactUserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d"),
                            GroupId = new Guid("0d9bcff0-57ea-45ed-a566-3c829942e34b"),
                            UserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596")
                        },
                        new
                        {
                            Id = new Guid("c7704f7c-f51d-4160-9459-f75131532903"),
                            ContactUserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5"),
                            GroupId = new Guid("a498dcb0-3f6d-4f39-a354-9af1e18f3d9e"),
                            UserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596")
                        },
                        new
                        {
                            Id = new Guid("b398b8c8-c896-4eb5-a05a-a7037c2a6d8b"),
                            ContactUserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162"),
                            GroupId = new Guid("95bba9f6-c661-425f-9902-dcb08e00d949"),
                            UserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596")
                        },
                        new
                        {
                            Id = new Guid("14845c01-8314-4569-872c-e8abb474a067"),
                            ContactUserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51"),
                            GroupId = new Guid("9ed9e0da-4c7e-4071-82ea-7f3617abde35"),
                            UserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596")
                        },
                        new
                        {
                            Id = new Guid("4d017a0e-10fc-4445-9211-63f59fe58dfe"),
                            ContactUserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2"),
                            GroupId = new Guid("04b8a481-221f-4bef-a5af-306204ced472"),
                            UserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5")
                        },
                        new
                        {
                            Id = new Guid("bd9e0c52-5ca1-4b6b-930d-b5b47992727b"),
                            ContactUserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d"),
                            GroupId = new Guid("167096b8-e066-46f0-a90e-446b540d331d"),
                            UserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5")
                        },
                        new
                        {
                            Id = new Guid("d674bd37-3f1c-4055-8e4f-265314ea729d"),
                            ContactUserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596"),
                            GroupId = new Guid("a498dcb0-3f6d-4f39-a354-9af1e18f3d9e"),
                            UserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5")
                        },
                        new
                        {
                            Id = new Guid("a6689f02-d9fa-4d29-8222-bc1c8278f740"),
                            ContactUserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162"),
                            GroupId = new Guid("7dc46b57-9f16-4857-9951-60b65e8d68ab"),
                            UserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5")
                        },
                        new
                        {
                            Id = new Guid("5b314bb3-3a91-4185-afef-08b161c2aef0"),
                            ContactUserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51"),
                            GroupId = new Guid("a5836c08-6aa5-4d85-8c18-af8019cdec9f"),
                            UserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5")
                        },
                        new
                        {
                            Id = new Guid("ea263365-2265-49f4-acb6-1f4627ca5abe"),
                            ContactUserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2"),
                            GroupId = new Guid("649a3553-5da3-4ce8-ad49-c51714bef758"),
                            UserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162")
                        },
                        new
                        {
                            Id = new Guid("bdfb7c71-94f6-4eaf-b44a-2dfc9da95cb4"),
                            ContactUserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d"),
                            GroupId = new Guid("169e4880-3d26-4e5b-a14c-c1e214d17370"),
                            UserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162")
                        },
                        new
                        {
                            Id = new Guid("2e463f58-a3b9-4c81-84da-8450f8a91467"),
                            ContactUserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596"),
                            GroupId = new Guid("95bba9f6-c661-425f-9902-dcb08e00d949"),
                            UserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162")
                        },
                        new
                        {
                            Id = new Guid("ae2f939b-8995-4e8c-8d84-ed59fd667d64"),
                            ContactUserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5"),
                            GroupId = new Guid("7dc46b57-9f16-4857-9951-60b65e8d68ab"),
                            UserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162")
                        },
                        new
                        {
                            Id = new Guid("ec87c7e3-6aab-4ac7-9c84-f408d7a38d6e"),
                            ContactUserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51"),
                            GroupId = new Guid("8f525afe-0b26-4e29-8edb-ebaa62721a4e"),
                            UserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162")
                        },
                        new
                        {
                            Id = new Guid("6286f15f-9d90-428f-9670-b6dd13110a4b"),
                            ContactUserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2"),
                            GroupId = new Guid("ffb2fe92-612f-41c2-b77c-b9027e430be1"),
                            UserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51")
                        },
                        new
                        {
                            Id = new Guid("906d3ae8-c93b-4710-a33c-9ac946a47931"),
                            ContactUserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d"),
                            GroupId = new Guid("a125b75d-abce-42f6-b876-f18978312f4d"),
                            UserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51")
                        },
                        new
                        {
                            Id = new Guid("5a12bb8f-6740-4c0d-86b8-4e8b1395234f"),
                            ContactUserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596"),
                            GroupId = new Guid("9ed9e0da-4c7e-4071-82ea-7f3617abde35"),
                            UserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51")
                        },
                        new
                        {
                            Id = new Guid("c49b428f-1f4b-4870-b4e7-441052630305"),
                            ContactUserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5"),
                            GroupId = new Guid("a5836c08-6aa5-4d85-8c18-af8019cdec9f"),
                            UserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51")
                        },
                        new
                        {
                            Id = new Guid("77d5673a-2b25-416a-854f-3c9fb537b914"),
                            ContactUserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162"),
                            GroupId = new Guid("8f525afe-0b26-4e29-8edb-ebaa62721a4e"),
                            UserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51")
                        });
                });

            modelBuilder.Entity("Domain.ContactInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("inviteduserid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_contactinvitations");

                    b.HasIndex("InvitedUserId")
                        .HasDatabaseName("ix_contactinvitations_inviteduserid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_contactinvitations_userid");

                    b.ToTable("contactinvitations");
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("groupid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sentat");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_messages_groupid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_messages_userid");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2"),
                            Email = "joao.teste@teste.com",
                            Nickname = "João"
                        },
                        new
                        {
                            Id = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d"),
                            Email = "leo.teste@teste.com",
                            Nickname = "Leo"
                        },
                        new
                        {
                            Id = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596"),
                            Email = "mariana.teste@teste.com",
                            Nickname = "Mariana"
                        },
                        new
                        {
                            Id = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5"),
                            Email = "matheus.teste@teste.com",
                            Nickname = "Matheus"
                        },
                        new
                        {
                            Id = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162"),
                            Email = "claudia.teste@teste.com",
                            Nickname = "Claudia"
                        },
                        new
                        {
                            Id = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51"),
                            Email = "luisfelipe.teste@teste.com",
                            Nickname = "Luís Felipe"
                        });
                });

            modelBuilder.Entity("Domain.UserAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashedpassword");

                    b.HasKey("UserId")
                        .HasName("pk_useraccounts");

                    b.ToTable("useraccounts");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2"),
                            HashedPassword = "$2a$11$THjcJYGrYHnJPG1Alf45LuJrPb7FaD0DIzqHvFxFpLtGu2r3A2Uye"
                        },
                        new
                        {
                            UserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d"),
                            HashedPassword = "$2a$11$Q2HYHdmUOXCrwDpiI52cv.ARAi6W5t8VnnLWd/0Iym9t7F5Ln.FQG"
                        },
                        new
                        {
                            UserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596"),
                            HashedPassword = "$2a$11$Z7ackKoxmCcV/kUDlNKGE.hP1VzE.S9BP07pQti2F0CCywmxRM/iK"
                        },
                        new
                        {
                            UserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5"),
                            HashedPassword = "$2a$11$fDU26b/yg9wha5ycDB5xaevpo/gePK/hxZEWj1U0.VyIaes6aPclG"
                        },
                        new
                        {
                            UserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162"),
                            HashedPassword = "$2a$11$6g5SQJ.uXTQITRnHyoidiO4q8TXaIlHxFk5P4zw0Y1Xr42ZKQWvXW"
                        },
                        new
                        {
                            UserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51"),
                            HashedPassword = "$2a$11$kCwbPSSCP.PFkBywyxvBjOfq5DSjOk338RwVL9TJ30os/8gk7StAO"
                        });
                });

            modelBuilder.Entity("Domain.UserGroupRelationship", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("groupid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("GroupId", "UserId")
                        .HasName("pk_usergrouprelationships");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_usergrouprelationships_groupid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usergrouprelationships_userid");

                    b.ToTable("usergrouprelationships");

                    b.HasData(
                        new
                        {
                            GroupId = new Guid("2b903f40-1f53-4c5b-beb3-b3cf5ac21ff3"),
                            UserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2")
                        },
                        new
                        {
                            GroupId = new Guid("998f3c13-78f1-42cb-977d-dfa121ae3609"),
                            UserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2")
                        },
                        new
                        {
                            GroupId = new Guid("04b8a481-221f-4bef-a5af-306204ced472"),
                            UserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2")
                        },
                        new
                        {
                            GroupId = new Guid("649a3553-5da3-4ce8-ad49-c51714bef758"),
                            UserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2")
                        },
                        new
                        {
                            GroupId = new Guid("ffb2fe92-612f-41c2-b77c-b9027e430be1"),
                            UserId = new Guid("d9f0c3e1-02f6-4ce5-bf74-b7c0f14cf2d2")
                        },
                        new
                        {
                            GroupId = new Guid("2b903f40-1f53-4c5b-beb3-b3cf5ac21ff3"),
                            UserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d")
                        },
                        new
                        {
                            GroupId = new Guid("0d9bcff0-57ea-45ed-a566-3c829942e34b"),
                            UserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d")
                        },
                        new
                        {
                            GroupId = new Guid("167096b8-e066-46f0-a90e-446b540d331d"),
                            UserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d")
                        },
                        new
                        {
                            GroupId = new Guid("169e4880-3d26-4e5b-a14c-c1e214d17370"),
                            UserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d")
                        },
                        new
                        {
                            GroupId = new Guid("a125b75d-abce-42f6-b876-f18978312f4d"),
                            UserId = new Guid("8a4b6a86-a053-46ac-9ba6-04eacaf5bf7d")
                        },
                        new
                        {
                            GroupId = new Guid("998f3c13-78f1-42cb-977d-dfa121ae3609"),
                            UserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596")
                        },
                        new
                        {
                            GroupId = new Guid("0d9bcff0-57ea-45ed-a566-3c829942e34b"),
                            UserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596")
                        },
                        new
                        {
                            GroupId = new Guid("a498dcb0-3f6d-4f39-a354-9af1e18f3d9e"),
                            UserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596")
                        },
                        new
                        {
                            GroupId = new Guid("95bba9f6-c661-425f-9902-dcb08e00d949"),
                            UserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596")
                        },
                        new
                        {
                            GroupId = new Guid("9ed9e0da-4c7e-4071-82ea-7f3617abde35"),
                            UserId = new Guid("3fc9e8d0-9a65-459f-ade4-57fe754f7596")
                        },
                        new
                        {
                            GroupId = new Guid("04b8a481-221f-4bef-a5af-306204ced472"),
                            UserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5")
                        },
                        new
                        {
                            GroupId = new Guid("167096b8-e066-46f0-a90e-446b540d331d"),
                            UserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5")
                        },
                        new
                        {
                            GroupId = new Guid("a498dcb0-3f6d-4f39-a354-9af1e18f3d9e"),
                            UserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5")
                        },
                        new
                        {
                            GroupId = new Guid("7dc46b57-9f16-4857-9951-60b65e8d68ab"),
                            UserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5")
                        },
                        new
                        {
                            GroupId = new Guid("a5836c08-6aa5-4d85-8c18-af8019cdec9f"),
                            UserId = new Guid("1e35ccb4-7d5a-4747-9cb0-62a875f44fd5")
                        },
                        new
                        {
                            GroupId = new Guid("649a3553-5da3-4ce8-ad49-c51714bef758"),
                            UserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162")
                        },
                        new
                        {
                            GroupId = new Guid("169e4880-3d26-4e5b-a14c-c1e214d17370"),
                            UserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162")
                        },
                        new
                        {
                            GroupId = new Guid("95bba9f6-c661-425f-9902-dcb08e00d949"),
                            UserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162")
                        },
                        new
                        {
                            GroupId = new Guid("7dc46b57-9f16-4857-9951-60b65e8d68ab"),
                            UserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162")
                        },
                        new
                        {
                            GroupId = new Guid("8f525afe-0b26-4e29-8edb-ebaa62721a4e"),
                            UserId = new Guid("4faaf336-27d2-4680-a2ae-78ec6c0b4162")
                        },
                        new
                        {
                            GroupId = new Guid("ffb2fe92-612f-41c2-b77c-b9027e430be1"),
                            UserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51")
                        },
                        new
                        {
                            GroupId = new Guid("a125b75d-abce-42f6-b876-f18978312f4d"),
                            UserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51")
                        },
                        new
                        {
                            GroupId = new Guid("9ed9e0da-4c7e-4071-82ea-7f3617abde35"),
                            UserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51")
                        },
                        new
                        {
                            GroupId = new Guid("a5836c08-6aa5-4d85-8c18-af8019cdec9f"),
                            UserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51")
                        },
                        new
                        {
                            GroupId = new Guid("8f525afe-0b26-4e29-8edb-ebaa62721a4e"),
                            UserId = new Guid("7b2601b8-0af4-43d3-9dda-f1db0cd7dd51")
                        });
                });

            modelBuilder.Entity("Domain.Contact", b =>
                {
                    b.HasOne("Domain.BlockInfo", "Block")
                        .WithOne()
                        .HasForeignKey("Domain.Contact", "BlockId")
                        .HasConstraintName("blockid");

                    b.HasOne("Domain.User", "ContactUser")
                        .WithMany()
                        .HasForeignKey("ContactUserId")
                        .HasConstraintName("contactuserid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ChatGroup", "Group")
                        .WithOne()
                        .HasForeignKey("Domain.Contact", "GroupId")
                        .HasConstraintName("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("ContactUser");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.ContactInvitation", b =>
                {
                    b.HasOne("Domain.User", "InvitedUser")
                        .WithMany()
                        .HasForeignKey("InvitedUserId")
                        .HasConstraintName("inviteduserid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.HasOne("Domain.ChatGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .HasConstraintName("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.UserAccount", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("Domain.UserAccount", "UserId")
                        .HasConstraintName("fk_useraccounts_users_userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.UserGroupRelationship", b =>
                {
                    b.HasOne("Domain.ChatGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .HasConstraintName("groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
